### ISSUE TITLE
Are the MISP user role checked?

### ISSUE THREAD

**Issue by adulau** [cybertier/mispbump#3]
Are the MISP user role checked?

- Is the user Org admin? or admin?

**Comment by felixpk** [comment]
> * admin? or admin?

Admin, because he must be able to create a sync server in order to completely automate this process.

> Are the MISP user role checked?

Not in the moment. But I will definitely see if there is a reliable way of checking the users permission (because role names and ids are customizable per instance) before he tries to make any changes.

**Comment by adulau** [comment]
Maybe you can do the following (in the recent version) you can generate config for sync:

- https://<YOURMISP>/servers/createSync.json

If you don't have sync role, you cannot generate it.

**Comment by felixpk** [comment]
I ended up downloading all roles from the MISP instance.

This way I can check very flexible what permissions a user has.

PR: #9
